name: CodSpeed
'on':
  push:
    branches:
    - main
  pull_request: null
  workflow_dispatch: null
env:
  RUSTFLAGS: --cfg uuid_unstable
permissions:
  contents: read
  id-token: write
jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Setup rust toolchain
      uses: moonrepo/setup-rust@v0
      with:
        channel: stable
        cache-target: release
    - name: Install dependencies
      run: pip install -r requirements.txt
    - name: Build the extension module
      run: 'pip install maturin

        RUSTFLAGS="--cfg uuid_unstable" maturin develop --release

        '
    - name: Run benchmarks
      uses: CodSpeedHQ/action@v4
      with:
        upload-url: ${{ secrets.CODSPEED_STAGING_UPLOAD_URL }}
        mode: simulation
        run: pytest tests/test_benchmarks.py --codspeed
